package dev.shreeman.nitro_fold_duo

import nitro.nitro_fold_duo_module.HybridNitroFoldDuoSpec

/// Native implementation of HybridNitroFoldDuoSpec.
/// This file is yours to edit — the interface is generated by `nitrogen generate`.
/// Use `applicationContext` (from the interface) to access the Android context.
class NitroFoldDuoImpl : HybridNitroFoldDuoSpec {

    override fun add(a: Double, b: Double): Double = a + b

    override suspend fun getGreeting(name: String): String = "Hello, $name!"
}
