// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.6
// Generated from: nitro_fold_duo.native.dart
// spec-sha256: a269e542d2224c6f3e54ee01721b10c2bcf409de637bacde11f9b7857cd3ed84
// ignore_for_file: no_leading_underscores_for_local_identifiers, prefer_typing_uninitialized_variables, non_constant_identifier_names, unused_element, unused_field
part of 'nitro_fold_duo.native.dart';

// --- Enum FFI helpers (generated by Nitrogen) ---

extension DuoHingeStatusNativeExt on DuoHingeStatus {
  int get nativeValue => index + 0;
}

extension DuoHingeStatusFromNativeExt on int {
  DuoHingeStatus toDuoHingeStatus() => DuoHingeStatus.values[this - 0];
}

extension DuoRegionKindNativeExt on DuoRegionKind {
  int get nativeValue => index + 0;
}

extension DuoRegionKindFromNativeExt on int {
  DuoRegionKind toDuoRegionKind() => DuoRegionKind.values[this - 0];
}

extension DuoVerticalBarEdgeNativeExt on DuoVerticalBarEdge {
  int get nativeValue => index + 0;
}

extension DuoVerticalBarEdgeFromNativeExt on int {
  DuoVerticalBarEdge toDuoVerticalBarEdge() =>
      DuoVerticalBarEdge.values[this - 0];
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

extension DuoReservedRegionRecordExt on DuoReservedRegion {
  static DuoReservedRegion fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static DuoReservedRegion fromReader(RecordReader r) => DuoReservedRegion(
    kind: r.readInt().toDuoRegionKind(),
    left: r.readDouble(),
    top: r.readDouble(),
    width: r.readDouble(),
    height: r.readDouble(),
    marginLeft: r.readDouble(),
    marginTop: r.readDouble(),
    marginRight: r.readDouble(),
    marginBottom: r.readDouble(),
    isActive: r.readBool(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(kind.nativeValue);
    writer.writeDouble(left);
    writer.writeDouble(top);
    writer.writeDouble(width);
    writer.writeDouble(height);
    writer.writeDouble(marginLeft);
    writer.writeDouble(marginTop);
    writer.writeDouble(marginRight);
    writer.writeDouble(marginBottom);
    writer.writeBool(isActive);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter.acquire();
    writeFields(writer);
    final ptr = writer.toNative(alloc);
    RecordWriter.release(writer);
    return ptr;
  }
}

extension DuoStateRecordExt on DuoState {
  static DuoState fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static DuoState fromReader(RecordReader r) => DuoState(
    isSupported: r.readBool(),
    hingeStatus: r.readInt().toDuoHingeStatus(),
    verticalBarEdge: r.readInt().toDuoVerticalBarEdge(),
    hingeAngle: r.readNullTag() ? null : r.readDouble(),
    regions: List.generate(
      r.readInt32(),
      (_) => DuoReservedRegionRecordExt.fromReader(r),
    ),
  );

  void writeFields(RecordWriter writer) {
    writer.writeBool(isSupported);
    writer.writeInt(hingeStatus.nativeValue);
    writer.writeInt(verticalBarEdge.nativeValue);
    writer.writeNullTag(hingeAngle == null);
    if (hingeAngle != null) {
      writer.writeDouble(hingeAngle!);
    }
    writer.writeInt32(regions.length);
    for (final e in regions) {
      e.writeFields(writer);
    }
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter.acquire();
    writeFields(writer);
    final ptr = writer.toNative(alloc);
    RecordWriter.release(writer);
    return ptr;
  }
}

extension DuoBarPressRecordExt on DuoBarPress {
  static DuoBarPress fromNative(Pointer<Uint8> ptr) =>
      fromReader(RecordReader.fromNative(ptr));

  static DuoBarPress fromReader(RecordReader r) => DuoBarPress(
    viewId: r.readInt(),
    index: r.readInt(),
    menuIndex: r.readInt(),
  );

  void writeFields(RecordWriter writer) {
    writer.writeInt(viewId);
    writer.writeInt(index);
    writer.writeInt(menuIndex);
  }

  Pointer<Uint8> toNative(Allocator alloc) {
    final writer = RecordWriter.acquire();
    writeFields(writer);
    final ptr = writer.toNative(alloc);
    RecordWriter.release(writer);
    return ptr;
  }
}

class _NitroFoldDuoImpl extends NitroFoldDuo {
  final DynamicLibrary _dylib;
  static final _instances = <String, WeakReference<_NitroFoldDuoImpl>>{};

  static final _instanceFinalizer =
      Finalizer<
        ({
          int id,
          String key,
          Pointer<NitroErrorFfi> err,
          void Function(int) destroy,
        })
      >((t) {
        try {
          t.destroy(t.id);
          NitroRuntime.releaseLib('nitro_fold_duo');
          if (_instances[t.key]?.target == null) _instances.remove(t.key);
        } catch (_) {
        } finally {
          calloc.free(t.err);
        }
      });
  final String _instanceKey;
  late final int _instanceId;
  final Pointer<NitroErrorFfi> _nitroErr = calloc<NitroErrorFfi>();
  late final void Function(Pointer<Void>) _nitroFreePtr = _dylib
      .lookupFunction<
        Void Function(Pointer<Void>),
        void Function(Pointer<Void>)
      >('nitro_fold_duo_nitro_free', isLeaf: true);
  void _nitroFree(Pointer<NativeType> ptr) => _nitroFreePtr(ptr.cast());
  late final Pointer<NativeFinalizerFunction> _nitroFreeFinalizer = _dylib
      .lookup<NativeFinalizerFunction>('nitro_fold_duo_nitro_free')
      .cast();
  late final Pointer<Void> Function(int) _nitroAllocPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(IntPtr),
        Pointer<Void> Function(int)
      >('nitro_fold_duo_nitro_alloc', isLeaf: true);
  late final void Function(int) _nitroAckPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_fold_duo_nitro_ack',
        isLeaf: true,
      );
  late final NitroNativeAllocator _nitroNativeAllocator = NitroNativeAllocator(
    _nitroAllocPtr,
    _nitroFreePtr,
  );

  static DynamicLibrary _loadSupportedLibrary() {
    return NitroRuntime.loadLibForTargets(
      'nitro_fold_duo',
      ios: true,
      android: true,
      macos: true,
      windows: true,
      linux: true,
      web: false,
    );
  }

  factory _NitroFoldDuoImpl([String key = 'default']) {
    final cached = _instances[key]?.target;
    if (cached != null) return cached;
    return _NitroFoldDuoImpl._init(key);
  }

  _NitroFoldDuoImpl._init(this._instanceKey)
    : _dylib = _loadSupportedLibrary() {
    final initSw = Stopwatch()..start();
    assert(
      sizeOf<IntPtr>() >= 4,
      'nitro_fold_duo: unsupported pointer width ${sizeOf<IntPtr>()}B',
    );
    final initFunc = _dylib
        .lookupFunction<
          IntPtr Function(Pointer<Void>),
          int Function(Pointer<Void>)
        >('nitro_fold_duo_init_dart_api_dl');
    final initCode = initFunc(NativeApi.initializeApiDLData);
    if (initCode != 0) {
      throw StateError(
        'nitro_fold_duo: Dart API DL initialization failed with code $initCode.',
      );
    }
    if (!_dylib.providesSymbol('nitro_fold_duo_nitro_abi_version')) {
      throw StateError(
        'nitro_fold_duo: missing nitro_fold_duo_nitro_abi_version — plugin must be rebuilt against the current Nitro version.',
      );
    }
    NitroRuntime.checkAbiVersion(
      'nitro_fold_duo',
      () => _dylib.lookupFunction<Uint32 Function(), int Function()>(
        'nitro_fold_duo_nitro_abi_version',
      )(),
    );
    if (!_dylib.providesSymbol('nitro_fold_duo_nitro_bridge_checksum')) {
      throw StateError(
        'nitro_fold_duo: missing nitro_fold_duo_nitro_bridge_checksum — plugin must be rebuilt against the current Nitro version.',
      );
    }
    NitroRuntime.checkLinkChecksum(
      'nitro_fold_duo',
      '4ec884f0f7a71402',
      () => _dylib
          .lookupFunction<Pointer<Utf8> Function(), Pointer<Utf8> Function()>(
            'nitro_fold_duo_nitro_bridge_checksum',
          )()
          .toDartString(),
    );
    final _keyPtr = _instanceKey.toNativeUtf8(allocator: calloc);
    try {
      _instanceId = _createInstancePtr(_keyPtr);
      if (_instanceId < 0) {
        throw StateError(
          'nitro_fold_duo: failed to create native instance for key "$_instanceKey".',
        );
      }
    } finally {
      calloc.free(_keyPtr);
    }
    NitroInstanceRegistry.register(_instanceId, this);
    _instances[_instanceKey] = WeakReference(this);
    _instanceFinalizer.attach(this, (
      id: _instanceId,
      key: _instanceKey,
      err: _nitroErr,
      destroy: _destroyInstancePtr,
    ), detach: this);
    initSw.stop();
    NitroRuntime.logLifecycle(
      'init(nitro_fold_duo)',
      'initialized in ${initSw.elapsedMicroseconds} µs (instanceId=$_instanceId)',
    );
  }

  late final int Function(Pointer<Utf8>) _createInstancePtr = _dylib
      .lookupFunction<
        Int64 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_fold_duo_create_instance');
  late final void Function(int) _destroyInstancePtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_fold_duo_destroy_instance',
      );
  late final Pointer<Uint8> Function(int, Pointer<NitroErrorFfi>)
  _currentStatePtr = _dylib
      .lookupFunction<
        Pointer<Uint8> Function(Int64, Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(int, Pointer<NitroErrorFfi>)
      >('nitro_fold_duo_current_state');
  late final void Function(
    int,
    int,
    Pointer<Uint8>,
    Pointer<Uint8>,
    int,
    int,
    bool,
    Pointer<NitroErrorFfi>,
  )
  _updateGlassCapsulePtr = _dylib
      .lookupFunction<
        Void Function(
          Int64,
          Int64,
          Pointer<Uint8>,
          Pointer<Uint8>,
          Int64,
          Int64,
          Bool,
          Pointer<NitroErrorFfi>,
        ),
        void Function(
          int,
          int,
          Pointer<Uint8>,
          Pointer<Uint8>,
          int,
          int,
          bool,
          Pointer<NitroErrorFfi>,
        )
      >('nitro_fold_duo_update_glass_capsule');
  late final void Function(
    int,
    int,
    int,
    Pointer<Uint8>,
    Pointer<Uint8>,
    Pointer<NitroErrorFfi>,
  )
  _setGlassCapsuleMenuPtr = _dylib
      .lookupFunction<
        Void Function(
          Int64,
          Int64,
          Int64,
          Pointer<Uint8>,
          Pointer<Uint8>,
          Pointer<NitroErrorFfi>,
        ),
        void Function(
          int,
          int,
          int,
          Pointer<Uint8>,
          Pointer<Uint8>,
          Pointer<NitroErrorFfi>,
        )
      >('nitro_fold_duo_set_glass_capsule_menu');
  late final void Function(int, int) _registerStateChangesPtr = _dylib
      .lookupFunction<Void Function(Int64, Int64), void Function(int, int)>(
        'nitro_fold_duo_register_state_changes_stream',
      );
  late final void Function(int) _releaseStateChangesPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_fold_duo_release_state_changes_stream',
      );
  late final void Function(int, int) _registerGlassCapsulePressesPtr = _dylib
      .lookupFunction<Void Function(Int64, Int64), void Function(int, int)>(
        'nitro_fold_duo_register_glass_capsule_presses_stream',
      );
  late final void Function(int) _releaseGlassCapsulePressesPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_fold_duo_release_glass_capsule_presses_stream',
      );
  // ignore: unused_field
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr = _dylib
      .lookupFunction<
        Pointer<NitroErrorFfi> Function(),
        Pointer<NitroErrorFfi> Function()
      >('nitro_fold_duo_get_error');
  // ignore: unused_field
  late final void Function() _clearErrorPtr = _dylib
      .lookupFunction<Void Function(), void Function()>(
        'nitro_fold_duo_clear_error',
      );

  @override
  void dispose() {
    if (isDisposed) return;
    _instanceFinalizer.detach(this);
    NitroRuntime.logLifecycle(
      'dispose(nitro_fold_duo)',
      'disposing (instanceId=$_instanceId)',
    );
    _destroyInstancePtr(_instanceId);
    NitroRuntime.releaseLib('nitro_fold_duo');
    _instances.remove(_instanceKey);
    NitroInstanceRegistry.unregister(_instanceId, this);
    calloc.free(_nitroErr); // S8: free pre-allocated error slot
    super.dispose(); // sets isDisposed = true, calls onDestroy()
    NitroRuntime.logLifecycle('dispose(nitro_fold_duo)', 'disposed');
  }

  /// Opaque reference to this native impl — pass to other plugins via AnyNativeObject.
  AnyNativeObject get asAnyNativeObject => AnyNativeObject(_instanceId);

  @override
  DuoState currentState() {
    checkDisposed();
    final t0 = NitroRuntime.syncStart('currentState');
    try {
      final res = _currentStatePtr(_instanceId, _nitroErr);
      NitroRuntime.throwIfOutParamError(
        _nitroErr,
        nativeFree: _nitroFree,
        methodName: 'currentState',
      );
      final DuoState decoded;
      try {
        decoded = DuoStateRecordExt.fromNative(res);
      } finally {
        _nitroFree(res);
      }
      return decoded;
    } finally {
      NitroRuntime.syncEnd(t0, 'currentState');
    }
  }

  @override
  void updateGlassCapsule(
    int viewId,
    List<String> symbols,
    List<String> titles,
    int selectedIndex,
    int tint,
    bool isDark,
  ) {
    checkDisposed();
    final t0 = NitroRuntime.syncStart('updateGlassCapsule');
    try {
      withArena((arena) {
        _updateGlassCapsulePtr(
          _instanceId,
          viewId,
          RecordWriter.encodeIndexedPrimitiveList(
            symbols,
            (w, e) => w.writeString(e),
            arena,
          ),
          RecordWriter.encodeIndexedPrimitiveList(
            titles,
            (w, e) => w.writeString(e),
            arena,
          ),
          selectedIndex,
          tint,
          isDark,
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(
          _nitroErr,
          nativeFree: _nitroFree,
          methodName: 'updateGlassCapsule',
        );
      });
    } finally {
      NitroRuntime.syncEnd(t0, 'updateGlassCapsule');
    }
  }

  @override
  void setGlassCapsuleMenu(
    int viewId,
    int buttonIndex,
    List<String> titles,
    List<String> symbols,
  ) {
    checkDisposed();
    final t0 = NitroRuntime.syncStart('setGlassCapsuleMenu');
    try {
      withArena((arena) {
        _setGlassCapsuleMenuPtr(
          _instanceId,
          viewId,
          buttonIndex,
          RecordWriter.encodeIndexedPrimitiveList(
            titles,
            (w, e) => w.writeString(e),
            arena,
          ),
          RecordWriter.encodeIndexedPrimitiveList(
            symbols,
            (w, e) => w.writeString(e),
            arena,
          ),
          _nitroErr,
        );
        NitroRuntime.throwIfOutParamError(
          _nitroErr,
          nativeFree: _nitroFree,
          methodName: 'setGlassCapsuleMenu',
        );
      });
    } finally {
      NitroRuntime.syncEnd(t0, 'setGlassCapsuleMenu');
    }
  }

  @override
  Stream<DuoState> get stateChanges {
    checkDisposed();
    return NitroRuntime.openStream<DuoState>(
      register: (port) => _registerStateChangesPtr(_instanceId, port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream stateChanges',
          );
        }
        final rawPtr = Pointer<Uint8>.fromAddress(message as int);
        try {
          return DuoStateRecordExt.fromNative(rawPtr);
        } finally {
          _nitroFree(rawPtr);
        }
      },
      release: (port) => _releaseStateChangesPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }

  @override
  Stream<DuoBarPress> get glassCapsulePresses {
    checkDisposed();
    DuoBarPress unpackItem(dynamic message) {
      if (message == null) {
        throw StateError(
          'Received null event on non-nullable stream glassCapsulePresses',
        );
      }
      final rawPtr = Pointer<Uint8>.fromAddress(message as int);
      try {
        return DuoBarPressRecordExt.fromNative(rawPtr);
      } finally {
        _nitroFree(rawPtr);
      }
    }

    return NitroRuntime.openStream<List<DuoBarPress>>(
      register: (port) => _registerGlassCapsulePressesPtr(_instanceId, port),
      unpack: (message) => [
        for (final m in message as List<dynamic>) unpackItem(m),
      ],
      release: (port) => _releaseGlassCapsulePressesPtr(port),
      backpressure: Backpressure.batch,
      ack: _nitroAckPtr,
    ).asyncExpand(Stream.fromIterable);
  }
}

extension NitroFoldDuoNativeRef on NitroFoldDuo {
  AnyNativeObject get asAnyNativeObject =>
      (this as _NitroFoldDuoImpl).asAnyNativeObject;
}

/// Default `throw UnimplementedError` bodies for every member of [NitroFoldDuo], so
/// hand-written fakes keep compiling when the spec grows:
/// `class FakeNitroFoldDuo extends NitroFoldDuo with NitroFoldDuoDefaults { /* overrides */ }`.
mixin NitroFoldDuoDefaults on NitroFoldDuo {
  @override
  DuoState currentState() =>
      throw UnimplementedError('NitroFoldDuo.currentState');
  @override
  void updateGlassCapsule(
    int viewId,
    List<String> symbols,
    List<String> titles,
    int selectedIndex,
    int tint,
    bool isDark,
  ) => throw UnimplementedError('NitroFoldDuo.updateGlassCapsule');
  @override
  void setGlassCapsuleMenu(
    int viewId,
    int buttonIndex,
    List<String> titles,
    List<String> symbols,
  ) => throw UnimplementedError('NitroFoldDuo.setGlassCapsuleMenu');
  @override
  Stream<DuoState> get stateChanges =>
      throw UnimplementedError('NitroFoldDuo.stateChanges');
  @override
  Stream<DuoBarPress> get glassCapsulePresses =>
      throw UnimplementedError('NitroFoldDuo.glassCapsulePresses');
}
