// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.6
// Generated from: nitro_fold_duo.native.dart
// spec-sha256: eabc08029258b07aaf4fdd1036323c0cbf6ace70dc03abef9ba237c54b478462
// ignore_for_file: no_leading_underscores_for_local_identifiers, prefer_typing_uninitialized_variables, non_constant_identifier_names, unused_element, unused_field
part of 'nitro_fold_duo.native.dart';

class _NitroFoldDuoImpl extends NitroFoldDuo {
  final DynamicLibrary _dylib;
  static final _instances = <String, WeakReference<_NitroFoldDuoImpl>>{};

  static final _instanceFinalizer =
      Finalizer<
        ({
          int id,
          String key,
          Pointer<NitroErrorFfi> err,
          void Function(int) destroy,
        })
      >((t) {
        try {
          t.destroy(t.id);
          NitroRuntime.releaseLib('nitro_fold_duo');
          if (_instances[t.key]?.target == null) _instances.remove(t.key);
        } catch (_) {
        } finally {
          calloc.free(t.err);
        }
      });
  final String _instanceKey;
  late final int _instanceId;
  final Pointer<NitroErrorFfi> _nitroErr = calloc<NitroErrorFfi>();
  late final void Function(Pointer<Void>) _nitroFreePtr = _dylib
      .lookupFunction<
        Void Function(Pointer<Void>),
        void Function(Pointer<Void>)
      >('nitro_fold_duo_nitro_free', isLeaf: true);
  void _nitroFree(Pointer<NativeType> ptr) => _nitroFreePtr(ptr.cast());
  late final Pointer<NativeFinalizerFunction> _nitroFreeFinalizer = _dylib
      .lookup<NativeFinalizerFunction>('nitro_fold_duo_nitro_free')
      .cast();
  late final Pointer<Void> Function(int) _nitroAllocPtr = _dylib
      .lookupFunction<
        Pointer<Void> Function(IntPtr),
        Pointer<Void> Function(int)
      >('nitro_fold_duo_nitro_alloc', isLeaf: true);
  late final void Function(int) _nitroAckPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_fold_duo_nitro_ack',
        isLeaf: true,
      );
  late final int Function(int) _nitroBindPtr = _dylib
      .lookupFunction<Int64 Function(Int64), int Function(int)>(
        'nitro_fold_duo_nitro_bind',
        isLeaf: true,
      );
  late final NitroCompletionBatch _nitroBatch = NitroCompletionBatch(
    bind: _nitroBindPtr,
    ack: _nitroAckPtr,
  );
  late final NitroNativeAllocator _nitroNativeAllocator = NitroNativeAllocator(
    _nitroAllocPtr,
    _nitroFreePtr,
  );

  static DynamicLibrary _loadSupportedLibrary() {
    return NitroRuntime.loadLibForTargets(
      'nitro_fold_duo',
      ios: true,
      android: true,
      macos: true,
      windows: true,
      linux: true,
      web: false,
    );
  }

  factory _NitroFoldDuoImpl([String key = 'default']) {
    final cached = _instances[key]?.target;
    if (cached != null) return cached;
    return _NitroFoldDuoImpl._init(key);
  }

  _NitroFoldDuoImpl._init(this._instanceKey)
    : _dylib = _loadSupportedLibrary() {
    final initSw = Stopwatch()..start();
    assert(
      sizeOf<IntPtr>() >= 4,
      'nitro_fold_duo: unsupported pointer width ${sizeOf<IntPtr>()}B',
    );
    final initFunc = _dylib
        .lookupFunction<
          IntPtr Function(Pointer<Void>),
          int Function(Pointer<Void>)
        >('nitro_fold_duo_init_dart_api_dl');
    final initCode = initFunc(NativeApi.initializeApiDLData);
    if (initCode != 0) {
      throw StateError(
        'nitro_fold_duo: Dart API DL initialization failed with code $initCode.',
      );
    }
    if (!_dylib.providesSymbol('nitro_fold_duo_nitro_abi_version')) {
      throw StateError(
        'nitro_fold_duo: missing nitro_fold_duo_nitro_abi_version — plugin must be rebuilt against the current Nitro version.',
      );
    }
    NitroRuntime.checkAbiVersion(
      'nitro_fold_duo',
      () => _dylib.lookupFunction<Uint32 Function(), int Function()>(
        'nitro_fold_duo_nitro_abi_version',
      )(),
    );
    if (!_dylib.providesSymbol('nitro_fold_duo_nitro_bridge_checksum')) {
      throw StateError(
        'nitro_fold_duo: missing nitro_fold_duo_nitro_bridge_checksum — plugin must be rebuilt against the current Nitro version.',
      );
    }
    NitroRuntime.checkLinkChecksum(
      'nitro_fold_duo',
      '9201f3d11f5579ba',
      () => _dylib
          .lookupFunction<Pointer<Utf8> Function(), Pointer<Utf8> Function()>(
            'nitro_fold_duo_nitro_bridge_checksum',
          )()
          .toDartString(),
    );
    final _keyPtr = _instanceKey.toNativeUtf8(allocator: calloc);
    try {
      _instanceId = _createInstancePtr(_keyPtr);
      if (_instanceId < 0) {
        throw StateError(
          'nitro_fold_duo: failed to create native instance for key "$_instanceKey".',
        );
      }
    } finally {
      calloc.free(_keyPtr);
    }
    NitroInstanceRegistry.register(_instanceId, this);
    _instances[_instanceKey] = WeakReference(this);
    _instanceFinalizer.attach(this, (
      id: _instanceId,
      key: _instanceKey,
      err: _nitroErr,
      destroy: _destroyInstancePtr,
    ), detach: this);
    initSw.stop();
    NitroRuntime.logLifecycle(
      'init(nitro_fold_duo)',
      'initialized in ${initSw.elapsedMicroseconds} µs (instanceId=$_instanceId)',
    );
  }

  late final int Function(Pointer<Utf8>) _createInstancePtr = _dylib
      .lookupFunction<
        Int64 Function(Pointer<Utf8>),
        int Function(Pointer<Utf8>)
      >('nitro_fold_duo_create_instance');
  late final void Function(int) _destroyInstancePtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_fold_duo_destroy_instance',
      );
  late final double Function(int, double, double, Pointer<NitroErrorFfi>)
  _addPtr = _dylib
      .lookup<
        NativeFunction<
          Double Function(Int64, Double, Double, Pointer<NitroErrorFfi>)
        >
      >('nitro_fold_duo_add')
      .asFunction<double Function(int, double, double, Pointer<NitroErrorFfi>)>(
        isLeaf: true,
      );
  late final void Function(int, Pointer<Utf8>, Pointer<NitroErrorFfi>, int)
  _getGreetingPtr = _dylib
      .lookupFunction<
        Void Function(Int64, Pointer<Utf8>, Pointer<NitroErrorFfi>, Int64),
        void Function(int, Pointer<Utf8>, Pointer<NitroErrorFfi>, int)
      >('nitro_fold_duo_get_greeting_dispatch');
  // ignore: unused_field
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr = _dylib
      .lookupFunction<
        Pointer<NitroErrorFfi> Function(),
        Pointer<NitroErrorFfi> Function()
      >('nitro_fold_duo_get_error');
  // ignore: unused_field
  late final void Function() _clearErrorPtr = _dylib
      .lookupFunction<Void Function(), void Function()>(
        'nitro_fold_duo_clear_error',
      );

  @override
  void dispose() {
    if (isDisposed) return;
    _instanceFinalizer.detach(this);
    NitroRuntime.logLifecycle(
      'dispose(nitro_fold_duo)',
      'disposing (instanceId=$_instanceId)',
    );
    _destroyInstancePtr(_instanceId);
    NitroRuntime.releaseLib('nitro_fold_duo');
    _instances.remove(_instanceKey);
    NitroInstanceRegistry.unregister(_instanceId, this);
    calloc.free(_nitroErr); // S8: free pre-allocated error slot
    super.dispose(); // sets isDisposed = true, calls onDestroy()
    NitroRuntime.logLifecycle('dispose(nitro_fold_duo)', 'disposed');
  }

  /// Opaque reference to this native impl — pass to other plugins via AnyNativeObject.
  AnyNativeObject get asAnyNativeObject => AnyNativeObject(_instanceId);

  @override
  double add(double a, double b) {
    checkDisposed();
    final t0 = NitroRuntime.syncStart('add');
    try {
      final res = _addPtr(_instanceId, a, b, _nitroErr);
      NitroRuntime.throwIfOutParamError(
        _nitroErr,
        nativeFree: _nitroFree,
        methodName: 'add',
      );
      return res;
    } finally {
      NitroRuntime.syncEnd(t0, 'add');
    }
  }

  @override
  Future<String> getGreeting(String name) async {
    checkDisposed();
    final arena = Arena();
    final _nitroErr = calloc<NitroErrorFfi>();
    try {
      return await NitroRuntime.openNativeAsync<String>(
        call: (port) => _getGreetingPtr(
          _instanceId,
          name.toNativeUtf8(allocator: arena),
          _nitroErr,
          port,
        ),
        unpack: (raw) {
          NitroRuntime.throwIfOutParamError(_nitroErr, nativeFree: _nitroFree);
          return ((raw) => raw as String)(raw);
        },
        cleanup: () => calloc.free(_nitroErr),
        batch: _nitroBatch,
        methodName: 'getGreeting',
      );
    } finally {
      arena.releaseAll();
    }
  }
}

extension NitroFoldDuoNativeRef on NitroFoldDuo {
  AnyNativeObject get asAnyNativeObject =>
      (this as _NitroFoldDuoImpl).asAnyNativeObject;
}

/// Default `throw UnimplementedError` bodies for every member of [NitroFoldDuo], so
/// hand-written fakes keep compiling when the spec grows:
/// `class FakeNitroFoldDuo extends NitroFoldDuo with NitroFoldDuoDefaults { /* overrides */ }`.
mixin NitroFoldDuoDefaults on NitroFoldDuo {
  @override
  double add(double a, double b) =>
      throw UnimplementedError('NitroFoldDuo.add');
  @override
  Future<String> getGreeting(String name) =>
      throw UnimplementedError('NitroFoldDuo.getGreeting');
}
