// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.6
// Generated from: nitro_fold_duo.native.dart
// spec-sha256: 3c64cfa4d32ae00cf6bda1c73ca92776745a17b877cc040b9f31862dc5a3d583
import Foundation
import Combine

@inline(__always)
private func _nitroStringFromCString(_ ptr: UnsafePointer<CChar>?) -> String {
    guard let ptr = ptr else { return "" }
    let len = Int(strlen(ptr))
    return String(decoding: UnsafeBufferPointer(start: UnsafeRawPointer(ptr).assumingMemoryBound(to: UInt8.self), count: len), as: UTF8.self)
}

@inline(__always)
private func _nitroStringOptFromCString(_ ptr: UnsafePointer<CChar>?) -> String? {
    ptr.map { p in
        let len = Int(strlen(p))
        return String(decoding: UnsafeBufferPointer(start: UnsafeRawPointer(p).assumingMemoryBound(to: UInt8.self), count: len), as: UTF8.self)
    }
}

@inline(__always)
private func _nitroStringToCString(_ s: String) -> UnsafeMutablePointer<CChar> {
    let utf8 = Array(s.utf8)
    let ptr = UnsafeMutablePointer<CChar>.allocate(capacity: utf8.count + 1)
    utf8.withUnsafeBytes { UnsafeMutableRawPointer(ptr).copyMemory(from: $0.baseAddress!, byteCount: utf8.count) }
    ptr[utf8.count] = 0
    return ptr
}

public protocol NitroEncodable {
    func toNative() -> UnsafeMutablePointer<UInt8>?
}

// --- Enums ---
public enum DuoHingeStatus: Int64 {
  case unknown = 0
  case closed = 1
  case partiallyOpen = 2
  case fullyOpen = 3
}

public enum DuoRegionKind: Int64 {
  case occlusion = 0
  case division = 1
}

public enum DuoVerticalBarEdge: Int64 {
  case unspecified = 0
  case leading = 1
  case trailing = 2
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

public struct DuoInsets: NitroEncodable {
  public var left: Double
  public var top: Double
  public var right: Double
  public var bottom: Double

  public init(left: Double, top: Double, right: Double, bottom: Double) {
    self.left = left
    self.top = top
    self.right = right
    self.bottom = bottom
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> DuoInsets {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> DuoInsets {
    return DuoInsets(
      left: r.readDouble(),
      top: r.readDouble(),
      right: r.readDouble(),
      bottom: r.readDouble()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeDouble(left)
    writer.writeDouble(top)
    writer.writeDouble(right)
    writer.writeDouble(bottom)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct DuoReservedRegion: NitroEncodable {
  public var kind: DuoRegionKind
  public var left: Double
  public var top: Double
  public var width: Double
  public var height: Double
  public var marginLeft: Double
  public var marginTop: Double
  public var marginRight: Double
  public var marginBottom: Double
  public var isActive: Bool

  public init(kind: DuoRegionKind, left: Double, top: Double, width: Double, height: Double, marginLeft: Double, marginTop: Double, marginRight: Double, marginBottom: Double, isActive: Bool) {
    self.kind = kind
    self.left = left
    self.top = top
    self.width = width
    self.height = height
    self.marginLeft = marginLeft
    self.marginTop = marginTop
    self.marginRight = marginRight
    self.marginBottom = marginBottom
    self.isActive = isActive
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> DuoReservedRegion {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> DuoReservedRegion {
    return DuoReservedRegion(
      kind: DuoRegionKind(rawValue: r.readInt())!,
      left: r.readDouble(),
      top: r.readDouble(),
      width: r.readDouble(),
      height: r.readDouble(),
      marginLeft: r.readDouble(),
      marginTop: r.readDouble(),
      marginRight: r.readDouble(),
      marginBottom: r.readDouble(),
      isActive: r.readBool()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(kind.rawValue)
    writer.writeDouble(left)
    writer.writeDouble(top)
    writer.writeDouble(width)
    writer.writeDouble(height)
    writer.writeDouble(marginLeft)
    writer.writeDouble(marginTop)
    writer.writeDouble(marginRight)
    writer.writeDouble(marginBottom)
    writer.writeBool(isActive)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct DuoState: NitroEncodable {
  public var isSupported: Bool
  public var hingeStatus: DuoHingeStatus
  public var verticalBarEdge: DuoVerticalBarEdge
  public var hingeAngle: Double?
  public var regions: [DuoReservedRegion]
  public var cornerInsets: DuoInsets

  public init(isSupported: Bool, hingeStatus: DuoHingeStatus, verticalBarEdge: DuoVerticalBarEdge, hingeAngle: Double?, regions: [DuoReservedRegion], cornerInsets: DuoInsets) {
    self.isSupported = isSupported
    self.hingeStatus = hingeStatus
    self.verticalBarEdge = verticalBarEdge
    self.hingeAngle = hingeAngle
    self.regions = regions
    self.cornerInsets = cornerInsets
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> DuoState {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> DuoState {
    return DuoState(
      isSupported: r.readBool(),
      hingeStatus: DuoHingeStatus(rawValue: r.readInt())!,
      verticalBarEdge: DuoVerticalBarEdge(rawValue: r.readInt())!,
      hingeAngle: r.readNullTag() ? nil : r.readDouble(),
      regions: (0..<Int(r.readInt32())).map { _ in DuoReservedRegion.fromReader(r) },
      cornerInsets: DuoInsets.fromReader(r)
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(isSupported)
    writer.writeInt(hingeStatus.rawValue)
    writer.writeInt(verticalBarEdge.rawValue)
    writer.writeNullTag(hingeAngle == nil)
    if let val = hingeAngle { writer.writeDouble(val) }
    writer.writeInt32(Int32(regions.count))
    for e in regions { e.writeFields(writer) }
    cornerInsets.writeFields(writer)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct DuoBarPress: NitroEncodable {
  public var viewId: Int64
  public var index: Int64
  public var menuIndex: Int64

  public init(viewId: Int64, index: Int64, menuIndex: Int64) {
    self.viewId = viewId
    self.index = index
    self.menuIndex = menuIndex
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> DuoBarPress {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> DuoBarPress {
    return DuoBarPress(
      viewId: r.readInt(),
      index: r.readInt(),
      menuIndex: r.readInt()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeInt(viewId)
    writer.writeInt(index)
    writer.writeInt(menuIndex)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct NitroNullableInt: NitroEncodable {
  public var hasValue: Bool
  public var value: Int64

  public init(hasValue: Bool, value: Int64) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroNullableInt {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroNullableInt {
    return NitroNullableInt(
      hasValue: r.readBool(),
      value: r.readInt()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeInt(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
  public var nullable: Int64? { hasValue ? value : nil }
  public static func fromNullable(_ v: Int64?) -> NitroNullableInt {
    return NitroNullableInt(hasValue: v != nil, value: v ?? 0)
  }
}

public struct NitroNullableDouble: NitroEncodable {
  public var hasValue: Bool
  public var value: Double

  public init(hasValue: Bool, value: Double) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroNullableDouble {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroNullableDouble {
    return NitroNullableDouble(
      hasValue: r.readBool(),
      value: r.readDouble()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeDouble(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
  public var nullable: Double? { hasValue ? value : nil }
  public static func fromNullable(_ v: Double?) -> NitroNullableDouble {
    return NitroNullableDouble(hasValue: v != nil, value: v ?? 0.0)
  }
}

public struct NitroNullableBool: NitroEncodable {
  public var hasValue: Bool
  public var value: Bool

  public init(hasValue: Bool, value: Bool) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroNullableBool {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroNullableBool {
    return NitroNullableBool(
      hasValue: r.readBool(),
      value: r.readBool()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeBool(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
  public var nullable: Bool? { hasValue ? value : nil }
  public static func fromNullable(_ v: Bool?) -> NitroNullableBool {
    return NitroNullableBool(hasValue: v != nil, value: v ?? false)
  }
}

public struct NitroOptInt64: NitroEncodable {
  public var hasValue: Bool
  public var value: Int64

  public init(hasValue: Bool, value: Int64) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroOptInt64 {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroOptInt64 {
    return NitroOptInt64(
      hasValue: r.readBool(),
      value: r.readInt()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeInt(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct NitroOptFloat64: NitroEncodable {
  public var hasValue: Bool
  public var value: Double

  public init(hasValue: Bool, value: Double) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroOptFloat64 {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroOptFloat64 {
    return NitroOptFloat64(
      hasValue: r.readBool(),
      value: r.readDouble()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeDouble(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct NitroOptBool: NitroEncodable {
  public var hasValue: Bool
  public var value: Bool

  public init(hasValue: Bool, value: Bool) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroOptBool {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroOptBool {
    return NitroOptBool(
      hasValue: r.readBool(),
      value: r.readBool()
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeBool(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public class NitroRecordWriter {
  public var bytes: [UInt8] = []
  public init() {}
  public func writeInt(_ v: Int64) {
      var val = v.littleEndian
      withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
  }
  public func writeInt32(_ v: Int32) {
      var val = v.littleEndian
      withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
  }
  public func writeDouble(_ v: Double) {
      var val = v.bitPattern.littleEndian
      withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
  }
  public func writeBool(_ v: Bool) {
      bytes.append(v ? 1 : 0)
  }
  public func writeString(_ v: String) {
      let utf8 = Array(v.utf8)
      writeInt32(Int32(utf8.count))
      bytes.append(contentsOf: utf8)
  }
  public func writeNullTag(_ isNull: Bool) {
      bytes.append(isNull ? 0 : 1)
  }
  public func writeBlob(_ v: Data) {
      writeInt32(Int32(v.count))
      bytes.append(contentsOf: Array(v))
  }
  public func toNative() -> UnsafeMutablePointer<UInt8>? {
      let total = 4 + bytes.count
      let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: total)
      var length = Int32(bytes.count).littleEndian
      _ = memcpy(ptr, &length, 4)
      if bytes.count > 0 {
          _ = memcpy(ptr.advanced(by: 4), bytes, bytes.count)
      }
      return ptr
  }
  public static func encodeList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
      let w = NitroRecordWriter()
      w.writeInt32(Int32(items.count))
      for item in items { writeItem(w, item) }
      return w.toNative()
  }
  /// Encodes a list of nullable items.
  /// Wire format: [4B count][for each: 1B hasValue][item bytes (only if hasValue)]
  /// Counterpart: NitroRecordReader.decodeNullableList / Dart RecordReader.decodeNullableList.
  public static func encodeNullableList<T>(_ items: [T?], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
      let w = NitroRecordWriter()
      w.writeInt32(Int32(items.count))
      for item in items {
          w.writeBool(item != nil)
          if let v = item { writeItem(w, v) }
      }
      return w.toNative()
  }
  /// Encodes a list with a per-item byte-offset table for O(1) random access.
  /// Wire format (payload after outer 4B length prefix):
  ///   [int32 count][int64 × count offsets from payload start][item bytes...]
  /// Counterpart: Dart LazyRecordList.decode / RecordWriter.encodeIndexedList.
  public static func encodeIndexedList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
      var blobs: [[UInt8]] = []
      for item in items {
          let w = NitroRecordWriter()
          writeItem(w, item)
          blobs.append(w.bytes)
      }
      var pos = 4 + 8 * blobs.count
      var offsets: [Int64] = []
      for blob in blobs {
          offsets.append(Int64(pos))
          pos += blob.count
      }
      let w = NitroRecordWriter()
      w.writeInt32(Int32(blobs.count))
      for off in offsets { w.writeInt(off) }
      for blob in blobs { w.bytes.append(contentsOf: blob) }
      return w.toNative()
  }
}

public class NitroRecordReader {
  public let bytes: UnsafeMutablePointer<UInt8>
  public var pos: Int = 0
  public init(ptr: UnsafeMutablePointer<UInt8>) {
      self.bytes = ptr.advanced(by: 4)
  }
  public init(payload: UnsafeMutablePointer<UInt8>) {
      self.bytes = payload
  }
  public func readInt() -> Int64 {
      var v: Int64 = 0
      _ = memcpy(&v, bytes.advanced(by: pos), 8)
      pos += 8
      return Int64(littleEndian: v)
  }
  public func readInt32() -> Int32 {
      var v: Int32 = 0
      _ = memcpy(&v, bytes.advanced(by: pos), 4)
      pos += 4
      return Int32(littleEndian: v)
  }
  public func readDouble() -> Double {
      var v: UInt64 = 0
      _ = memcpy(&v, bytes.advanced(by: pos), 8)
      pos += 8
      return Double(bitPattern: UInt64(littleEndian: v))
  }
  public func readBool() -> Bool {
      let v = bytes[pos]
      pos += 1
      return v != 0
  }
  public func readString() -> String {
      let len = Int(readInt32())
      guard len > 0 else { return "" }
      let s = String(bytes: UnsafeBufferPointer(start: bytes.advanced(by: pos), count: len), encoding: .utf8) ?? ""
      pos += len
      return s
  }
  public func readNullTag() -> Bool {
      let v = bytes[pos]
      pos += 1
      return v == 0
  }
  public func readBlob() -> Data {
      let len = Int(readInt32())
      let data = Data(bytes: bytes.advanced(by: pos), count: len)
      pos += len
      return data
  }
  public func readBlobAsPointer() -> UnsafeMutablePointer<UInt8>? {
      let len = Int(readInt32())
      if (len == 0) { return nil }
      let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: len)
      ptr.initialize(from: bytes.advanced(by: pos), count: len)
      pos += len
      return ptr
  }
  public static func decodeList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
      let r = NitroRecordReader(ptr: ptr)
      let count = r.readInt32()
      var items: [T] = []
      for _ in 0..<count {
          items.append(readItem(r))
      }
      return items
  }
  /// Decodes a list of nullable items.
  /// Wire format: [4B count][for each: 1B hasValue][item bytes (only if hasValue)]
  /// Counterpart: NitroRecordWriter.encodeNullableList / Dart RecordWriter.encodeNullableList.
  public static func decodeNullableList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T?] {
      let r = NitroRecordReader(ptr: ptr)
      let count = r.readInt32()
      var items: [T?] = []
      for _ in 0..<count {
          let hasValue = r.readBool()
          items.append(hasValue ? readItem(r) : nil)
      }
      return items
  }
  /// Decodes a list encoded by Dart's RecordWriter.encodeIndexedList / encodeIndexedPrimitiveList.
  /// Wire format (payload after outer 4B length prefix):
  ///   [int32 count][int64 × count offsets from payload start][item bytes...]
  /// The offset table is skipped; items are read sequentially after it.
  public static func decodeIndexedList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
      let r = NitroRecordReader(ptr: ptr)
      let count = r.readInt32()
      r.pos += Int(count) * 8  // skip Int64 offset table
      var items: [T] = []
      for _ in 0..<count {
          items.append(readItem(r))
      }
      return items
  }
}

/**
 * Protocol for the NitroFoldDuo module.
 * Conform to this in your Swift source code.
 * Nitro may call this implementation from any native thread.
 * Keep mutable state thread-safe or marshal work onto your own queue/actor.
 */
public protocol HybridNitroFoldDuoProtocol: AnyObject {
    // source: nitro_fold_duo.native.dart:154
    func currentState() -> DuoState
    // source: nitro_fold_duo.native.dart:171
    func updateGlassCapsule(viewId: Int64, symbols: [String], titles: [String], selectedIndex: Int64, tint: Int64, isDark: Bool) -> Void
    // source: nitro_fold_duo.native.dart:187
    func updateGlassSurface(viewId: Int64, cornerRadius: Double, tint: Int64, isDark: Bool) -> Void
    // source: nitro_fold_duo.native.dart:200
    func setGlassCapsuleMenu(viewId: Int64, buttonIndex: Int64, titles: [String], symbols: [String]) -> Void
    var stateChanges: AnyPublisher<DuoState, Never> { get }
    var glassCapsulePresses: AnyPublisher<DuoBarPress, Never> { get }
}

public class NitroFoldDuoRegistry {
    public static var impl: HybridNitroFoldDuoProtocol?

    public static func register(_ impl: HybridNitroFoldDuoProtocol) {
        NitroFoldDuoRegistry.impl = impl
    }

    // Stream: stateChanges cancellables keyed by dartPort
    public static var _stateChangesCancellables = [Int64: AnyCancellable]()

    // Stream: glassCapsulePresses cancellables keyed by dartPort
    public static var _glassCapsulePressesCancellables = [Int64: AnyCancellable]()
    public static var _glassCapsulePressesFlushTimers: [Int64: DispatchSourceTimer] = [:]
}

// MARK: - C bridge stubs — exported as C symbols called by the generated .cpp shim

// source: nitro_fold_duo.native.dart:154
@_cdecl("_nitro_fold_duo_call_currentState")
public func _nitro_fold_duo_call_currentState() -> UnsafeMutableRawPointer? {
    guard let impl = NitroFoldDuoRegistry.impl else { return nil }
    return impl.currentState().toNative().map { UnsafeMutableRawPointer($0) }
}

// source: nitro_fold_duo.native.dart:171
@_cdecl("_nitro_fold_duo_call_updateGlassCapsule")
public func _nitro_fold_duo_call_updateGlassCapsule(_ viewId: Int64, _ symbols: UnsafeMutableRawPointer?, _ titles: UnsafeMutableRawPointer?, _ selectedIndex: Int64, _ tint: Int64, _ isDark: Int8) -> Void {
    let symbolsPtr = symbols?.assumingMemoryBound(to: UInt8.self)
    let symbolsDecoded = symbolsPtr.map { NitroRecordReader.decodeIndexedList($0) { r in r.readString() } } ?? []
    let titlesPtr = titles?.assumingMemoryBound(to: UInt8.self)
    let titlesDecoded = titlesPtr.map { NitroRecordReader.decodeIndexedList($0) { r in r.readString() } } ?? []
    NitroFoldDuoRegistry.impl?.updateGlassCapsule(viewId: viewId, symbols: symbolsDecoded, titles: titlesDecoded, selectedIndex: selectedIndex, tint: tint, isDark: isDark != 0)
}

// source: nitro_fold_duo.native.dart:187
@_cdecl("_nitro_fold_duo_call_updateGlassSurface")
public func _nitro_fold_duo_call_updateGlassSurface(_ viewId: Int64, _ cornerRadius: Double, _ tint: Int64, _ isDark: Int8) -> Void {
    NitroFoldDuoRegistry.impl?.updateGlassSurface(viewId: viewId, cornerRadius: cornerRadius, tint: tint, isDark: isDark != 0)
}

// source: nitro_fold_duo.native.dart:200
@_cdecl("_nitro_fold_duo_call_setGlassCapsuleMenu")
public func _nitro_fold_duo_call_setGlassCapsuleMenu(_ viewId: Int64, _ buttonIndex: Int64, _ titles: UnsafeMutableRawPointer?, _ symbols: UnsafeMutableRawPointer?) -> Void {
    let titlesPtr = titles?.assumingMemoryBound(to: UInt8.self)
    let titlesDecoded = titlesPtr.map { NitroRecordReader.decodeIndexedList($0) { r in r.readString() } } ?? []
    let symbolsPtr = symbols?.assumingMemoryBound(to: UInt8.self)
    let symbolsDecoded = symbolsPtr.map { NitroRecordReader.decodeIndexedList($0) { r in r.readString() } } ?? []
    NitroFoldDuoRegistry.impl?.setGlassCapsuleMenu(viewId: viewId, buttonIndex: buttonIndex, titles: titlesDecoded, symbols: symbolsDecoded)
}

@_cdecl("_nitro_fold_duo_register_stateChanges_stream")
public func _nitro_fold_duo_register_stateChanges_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, UnsafeMutablePointer<UInt8>?) -> Bool
) {
    NitroFoldDuoRegistry._stateChangesCancellables[dartPort] =
        NitroFoldDuoRegistry.impl?.stateChanges.sink { item in
            let raw = item.toNative()
            if !emitCb(dartPort, raw) {
                if let raw { free(UnsafeMutableRawPointer(raw)) }
                NitroFoldDuoRegistry._stateChangesCancellables.removeValue(forKey: dartPort)?.cancel()
            }
        }
}

@_cdecl("_nitro_fold_duo_release_stateChanges_stream")
public func _nitro_fold_duo_release_stateChanges_stream(_ dartPort: Int64) {
    NitroFoldDuoRegistry._stateChangesCancellables[dartPort]?.cancel()
    NitroFoldDuoRegistry._stateChangesCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_fold_duo_register_glassCapsulePresses_stream")
public func _nitro_fold_duo_register_glassCapsulePresses_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, UnsafeMutablePointer<UInt8>?) -> Bool
) {
    NitroFoldDuoRegistry._glassCapsulePressesCancellables[dartPort] =
        NitroFoldDuoRegistry.impl?.glassCapsulePresses.sink { item in
            let raw = item.toNative()
            if !emitCb(dartPort, raw) {
                if let raw { free(UnsafeMutableRawPointer(raw)) }
                NitroFoldDuoRegistry._glassCapsulePressesCancellables.removeValue(forKey: dartPort)?.cancel()
            }
        }
}

@_cdecl("_nitro_fold_duo_release_glassCapsulePresses_stream")
public func _nitro_fold_duo_release_glassCapsulePresses_stream(_ dartPort: Int64) {
    NitroFoldDuoRegistry._glassCapsulePressesCancellables[dartPort]?.cancel()
    NitroFoldDuoRegistry._glassCapsulePressesCancellables.removeValue(forKey: dartPort)
}
