import Combine
import Foundation

/// Native implementation of HybridNitroFoldDuoProtocol.
/// This file is yours to edit — the protocol is generated by `nitrogen generate`.
///
/// `currentState` and the three `…Glass…` methods are `@nitroFast` on the Dart
/// side: leaf calls with no error slot. They must never throw, never block and
/// never call back into Dart — which is why each one only reads a cached value
/// or hands its arguments to the main thread and returns.
public class NitroFoldDuoImpl: NSObject, HybridNitroFoldDuoProtocol {

    private let box = DuoStateBox()

    public override init() {
        super.init()
        let box = self.box
        Task { @MainActor in
            DuoFoldWatcher.shared = DuoFoldWatcher(box: box)
        }
    }


    public func currentState() -> DuoState {
        return box.current
    }

    public var stateChanges: AnyPublisher<DuoState, Never> {
        return box.subject.eraseToAnyPublisher()
    }

    public func updateGlassCapsule(
        viewId: Int64, symbols: [String], titles: [String], selectedIndex: Int64,
        tint: Int64, isDark: Bool
    ) {
        // Called from Dart's UI isolate; UIKit is main-thread only.
        Task { @MainActor in
            DuoGlassCapsuleRegistry.apply(
                id: viewId, symbols: symbols, titles: titles,
                selectedIndex: Int(selectedIndex), tint: Int(tint), isDark: isDark)
        }
    }

    public func updateGlassSurface(
        viewId: Int64, cornerRadius: Double, tint: Int64, isDark: Bool
    ) {
        Task { @MainActor in
            DuoGlassSurfaceRegistry.apply(
                id: viewId, cornerRadius: cornerRadius, tint: Int(tint),
                isDark: isDark)
        }
    }

    public func setGlassCapsuleMenu(
        viewId: Int64, buttonIndex: Int64, titles: [String], symbols: [String]
    ) {
        Task { @MainActor in
            DuoGlassCapsuleRegistry.setMenu(
                id: viewId, buttonIndex: Int(buttonIndex), titles: titles,
                symbols: symbols)
        }
    }

    public var glassCapsulePresses: AnyPublisher<DuoBarPress, Never> {
        return DuoCapsuleBus.shared.presses.eraseToAnyPublisher()
    }
}
