// HybridNitroFoldDuo — WindowsNativeImpl.cpp implementation.
// Generated by nitrogen link. Fill in the method bodies.
#include "../../lib/src/generated/cpp/nitro_fold_duo.native.g.h"

#include <string>

class HybridNitroFoldDuoImpl final : public HybridNitroFoldDuo {
public:
    // TODO: implement all pure-virtual methods declared in HybridNitroFoldDuo
};

// MSVC static-initializer auto-registration (no __attribute__((constructor)) on Windows).
namespace {
  struct _AutoRegister {
    _AutoRegister() { nitro_fold_duo_register_impl(new HybridNitroFoldDuoImpl()); }
  };
  static _AutoRegister _auto_register_instance;
}
