// HybridNitroFoldDuo — LinuxNativeImpl.cpp implementation.
// Generated by nitrogen init. Fill in the method bodies.
#include "../../lib/src/generated/cpp/nitro_fold_duo.native.g.h"

#include <string>

class HybridNitroFoldDuoImpl final : public HybridNitroFoldDuo {
public:
    // TODO: implement all pure-virtual methods declared in HybridNitroFoldDuo
};

// GCC/Clang auto-registration via constructor attribute.
__attribute__((constructor))
static void nitro_auto_register() {
    nitro_fold_duo_register_impl(new HybridNitroFoldDuoImpl());
}
