// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.6
// Generated from: nitro_fold_duo.native.dart
// spec-sha256: 0240db7d8a98501cbeea458c605b5e38e7c883ec2ad860e3330f97f958ee4cda
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>
#include <string>
#if defined(__APPLE__)
#import <Foundation/Foundation.h>
#endif
#if defined(__ANDROID__) || defined(__linux__)
#include <dlfcn.h>
#endif
#include "dart_api_dl.h"
#include "nitro_fold_duo.bridge.g.h"
#include "nitro_completion_batch.h"
static NitroCompletionBatch g_nitro_batch_nitro_fold_duo;
extern "C" {
NITRO_EXPORT bool nitro_fold_duo_nitro_post(int64_t port, struct _Dart_CObject* obj) { return g_nitro_batch_nitro_fold_duo.post(port, obj); }
NITRO_EXPORT int64_t nitro_fold_duo_nitro_bind(int64_t batchPort) { return g_nitro_batch_nitro_fold_duo.bind(batchPort); }
NITRO_EXPORT void nitro_fold_duo_nitro_ack(int64_t batchPort) { g_nitro_batch_nitro_fold_duo.ack(batchPort); }
}


#if defined(_MSC_VER) && !defined(strdup)
#define strdup _strdup
#endif

extern "C" {
NITRO_EXPORT uint32_t nitro_fold_duo_nitro_abi_version(void) {
    return 1;
}
NITRO_EXPORT const char* nitro_fold_duo_nitro_bridge_checksum(void) {
    return "4f0743947bf6907b";
}
NITRO_EXPORT intptr_t nitro_fold_duo_init_dart_api_dl(void* data) {
    return Dart_InitializeApiDL(data);
}
}
static thread_local NitroError g_nitro_error = { 0, nullptr, nullptr, nullptr, nullptr };
alignas(8) static thread_local uint8_t _g_opt_ret[16];
static thread_local std::string _g_str_ret;

extern "C" {
NitroError* nitro_fold_duo_get_error() { return &g_nitro_error; }
void nitro_fold_duo_clear_error() {
    g_nitro_error.hasError = 0;
    if (g_nitro_error.name) { free((void*)g_nitro_error.name); g_nitro_error.name = nullptr; }
    if (g_nitro_error.message) { free((void*)g_nitro_error.message); g_nitro_error.message = nullptr; }
    if (g_nitro_error.code) { free((void*)g_nitro_error.code); g_nitro_error.code = nullptr; }
    if (g_nitro_error.stackTrace) { free((void*)g_nitro_error.stackTrace); g_nitro_error.stackTrace = nullptr; }
}

static void nitro_report_error(const char* name, const char* message, const char* code, const char* stack) {
    nitro_fold_duo_clear_error();
    g_nitro_error.hasError = 1;
    g_nitro_error.name = name ? strdup(name) : strdup("NativeException");
    g_nitro_error.message = message ? strdup(message) : strdup("An unknown native exception occurred.");
    g_nitro_error.code = code ? strdup(code) : nullptr;
    g_nitro_error.stackTrace = stack ? strdup(stack) : nullptr;
}
}

#if defined(__ANDROID__) || defined(__linux__)
static void* _nitro_fold_duo_lib_h = nullptr;
#endif

extern "C" {
// Finding 1: promotes this native library to process-wide visibility so that
// @Native<F>() Dart bindings resolve via DynamicLibrary.process() on Android/Linux.
// On iOS/macOS this is a no-op — symbols are already in the process namespace
// via static linking.  Call once from the Kotlin/Swift plugin init.
NITRO_EXPORT void nitro_fold_duo_enable_native_bindings(void) {
#if defined(__ANDROID__) || defined(__linux__)
    if (!_nitro_fold_duo_lib_h) {
        Dl_info info;
        if (dladdr((void*)nitro_fold_duo_enable_native_bindings, &info) && info.dli_fname) {
            // RTLD_GLOBAL | RTLD_NOLOAD promotes already-loaded lib to global namespace
            // without re-loading it, making symbols available to DynamicLibrary.process().
            _nitro_fold_duo_lib_h = dlopen(info.dli_fname, RTLD_LAZY | RTLD_GLOBAL | RTLD_NOLOAD);
        }
    }
#endif
}
}

#ifdef __ANDROID__
#include <jni.h>
#include <android/log.h>
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, "Nitrogen", __VA_ARGS__)

static JavaVM* g_jvm = nullptr;
static jclass g_bridgeClass = nullptr;

// ── Cached JNI IDs (initialized once in JNI_OnLoad, safe to use from any thread) ──
static jmethodID g_exc_getName = nullptr;
static jmethodID g_exc_getMessage = nullptr;
static jmethodID g_mid_create_instance_call = nullptr;
static jmethodID g_mid_destroy_instance_call = nullptr;
static jmethodID g_mid_currentState_call = nullptr;
static jmethodID g_mid_updateGlassCapsule_call = nullptr;
static jmethodID g_mid_updateGlassSurface_call = nullptr;
static jmethodID g_mid_setGlassCapsuleMenu_call = nullptr;
static jmethodID g_mid_nitro_fold_duo_register_state_changes_stream_call = nullptr;
static jmethodID g_mid_nitro_fold_duo_release_state_changes_stream_call = nullptr;
static jmethodID g_mid_nitro_fold_duo_register_glass_capsule_presses_stream_call = nullptr;
static jmethodID g_mid_nitro_fold_duo_release_glass_capsule_presses_stream_call = nullptr;
static jclass g_cls_DuoState = nullptr;
static jmethodID g_mid_DuoState_encode = nullptr;
static jclass g_cls_DuoBarPress = nullptr;
static jmethodID g_mid_DuoBarPress_encode = nullptr;


// RAII guard: auto-detaches a thread from the JVM when it exits.
// One instance is stored in thread-local storage; its destructor fires
// when the thread terminates, ensuring no JVM thread descriptor leaks.
struct NitroJniThreadGuard {
    bool attached = false;
    ~NitroJniThreadGuard() {
        if (attached && g_jvm != nullptr) {
            g_jvm->DetachCurrentThread();
        }
    }
};
static thread_local NitroJniThreadGuard g_thread_guard;

static void nitro_report_jni_exception(JNIEnv* env, jthrowable ex, NitroError* _nitro_err) {
    // MUST clear the pending exception before making any further JNI calls.
    // JNI aborts if any JNI function (e.g. GetObjectClass) is called while
    // an exception is still pending.
    env->ExceptionClear();
    jclass ex_class = env->GetObjectClass(ex);
    jstring j_name = (jstring)env->CallObjectMethod(ex_class, g_exc_getName);
    const char* name = (j_name != nullptr) ? env->GetStringUTFChars(j_name, 0) : "JavaException";

    jstring j_msg = (jstring)env->CallObjectMethod(ex, g_exc_getMessage);
    const char* msg = (j_msg != nullptr) ? env->GetStringUTFChars(j_msg, 0) : "No message provided";

    // S8: write to out-param slot (sync) or TLS slot (async, _nitro_err == nullptr).
    if (_nitro_err) {
        _nitro_err->hasError = 1;
        _nitro_err->name       = strdup(name);
        _nitro_err->message    = strdup(msg);
        _nitro_err->code       = nullptr;
        _nitro_err->stackTrace = nullptr;
    } else {
        // Async functions use TLS slot (read by callAsync via get_error/clear_error).
        nitro_report_error(name, msg, nullptr, nullptr);
    }

    if (j_name) {
        env->ReleaseStringUTFChars(j_name, name);
        env->DeleteLocalRef(j_name);
    }
    if (j_msg) {
        env->ReleaseStringUTFChars(j_msg, msg);
        env->DeleteLocalRef(j_msg);
    }
    env->DeleteLocalRef(ex_class);
    env->DeleteLocalRef(ex);
}


extern "C" {

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved) {
    g_jvm = vm;
    __android_log_print(ANDROID_LOG_INFO, "Nitrogen", "JNI_OnLoad called for nitro_fold_duo");
    JNIEnv* env = nullptr;
    if (vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6) != JNI_OK) {
        return -1;
    }
    // Cache standard-library method IDs only — system class loader is always
    // available here. Application class IDs are deferred to initialize().
    {
        jclass cls_class = env->FindClass("java/lang/Class");
        if (cls_class) { g_exc_getName = env->GetMethodID(cls_class, "getName", "()Ljava/lang/String;"); env->DeleteLocalRef(cls_class); }
        jclass throwable_class = env->FindClass("java/lang/Throwable");
        if (throwable_class) { g_exc_getMessage = env->GetMethodID(throwable_class, "getMessage", "()Ljava/lang/String;"); env->DeleteLocalRef(throwable_class); }
    }
    return JNI_VERSION_1_6;
}

static JNIEnv* GetEnv() {
    if (g_jvm == nullptr) { return nullptr; }
    JNIEnv* env = nullptr;
    int status = g_jvm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
    if (status == JNI_EDETACHED) {
        g_jvm->AttachCurrentThread(&env, nullptr);
        g_thread_guard.attached = true; // will DetachCurrentThread on thread exit
    }
    return env;
}

NITRO_EXPORT void nitro_fold_duo_nitro_free(void* ptr) { if (ptr) { free(ptr); } }
NITRO_EXPORT void* nitro_fold_duo_nitro_alloc(size_t size) { return malloc(size); }

NITRO_EXPORT int64_t nitro_fold_duo_create_instance(const char* key) {
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return -1; }
    jmethodID mid = g_mid_create_instance_call;
    if (mid == nullptr) { LOGE("create_instance_call JNI method not cached"); return -1; }
    jstring j_key = env->NewStringUTF(key ? key : "default");
    jlong id = env->CallStaticLongMethod(g_bridgeClass, mid, j_key);
    env->DeleteLocalRef(j_key);
    if (env->ExceptionCheck()) { env->ExceptionClear(); LOGE("create_instance_call threw"); return -1; }
    return (int64_t)id;
}

NITRO_EXPORT void nitro_fold_duo_destroy_instance(int64_t instanceId) {
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return; }
    jmethodID mid = g_mid_destroy_instance_call;
    if (mid == nullptr) { LOGE("destroy_instance_call JNI method not cached"); return; }
    env->CallStaticVoidMethod(g_bridgeClass, mid, (jlong)instanceId);
    if (env->ExceptionCheck()) { env->ExceptionClear(); }
}

void* nitro_fold_duo_current_state(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return nullptr; }
    jmethodID methodId = g_mid_currentState_call;
    if (methodId == nullptr) { LOGE("Method not found: currentState_call sig=(J)[B"); return nullptr; }

    nitro_fold_duo_clear_error();
    if (env->PushLocalFrame(16) != 0) { return nullptr; }
    jbyteArray jarr = (jbyteArray)env->CallStaticObjectMethod(g_bridgeClass, methodId, (jlong)instanceId);
    if (env->ExceptionCheck()) {
        nitro_report_jni_exception(env, env->ExceptionOccurred(), _nitro_err);
        env->PopLocalFrame(nullptr);
        return nullptr;
    }
    if (jarr == nullptr) {
        env->PopLocalFrame(nullptr);
        return nullptr;
    }
    jsize len = env->GetArrayLength(jarr);
    uint8_t* result = (uint8_t*)malloc(len);
    env->GetByteArrayRegion(jarr, 0, len, (jbyte*)result);
    env->PopLocalFrame(nullptr);
    return result;
}

void nitro_fold_duo_update_glass_capsule(int64_t instanceId, int64_t viewId, void* symbols, void* titles, int64_t selectedIndex, int64_t tint, double symbolPointSize, int8_t isDark, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return; }
    jmethodID methodId = g_mid_updateGlassCapsule_call;
    if (methodId == nullptr) { LOGE("Method not found: updateGlassCapsule_call sig=(JJ[B[BJJDZ)V"); return; }

    nitro_fold_duo_clear_error();
    if (env->PushLocalFrame(16) != 0) { return; }
    int32_t symbols_payload_len = *((const int32_t*)symbols);
    int32_t symbols_total = symbols_payload_len + 4;
    jbyteArray j_symbols = env->NewByteArray((jsize)symbols_total);
    env->SetByteArrayRegion(j_symbols, 0, (jsize)symbols_total, (const jbyte*)symbols);
    int32_t titles_payload_len = *((const int32_t*)titles);
    int32_t titles_total = titles_payload_len + 4;
    jbyteArray j_titles = env->NewByteArray((jsize)titles_total);
    env->SetByteArrayRegion(j_titles, 0, (jsize)titles_total, (const jbyte*)titles);
    env->CallStaticVoidMethod(g_bridgeClass, methodId, (jlong)instanceId, viewId, j_symbols, j_titles, selectedIndex, tint, symbolPointSize, isDark);
    env->PopLocalFrame(nullptr);
    if (env->ExceptionCheck()) { nitro_report_jni_exception(env, env->ExceptionOccurred(), _nitro_err); }
}

void nitro_fold_duo_update_glass_surface(int64_t instanceId, int64_t viewId, double cornerRadius, int64_t tint, int8_t isDark, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return; }
    jmethodID methodId = g_mid_updateGlassSurface_call;
    if (methodId == nullptr) { LOGE("Method not found: updateGlassSurface_call sig=(JJDJZ)V"); return; }

    nitro_fold_duo_clear_error();
    if (env->PushLocalFrame(16) != 0) { return; }
    env->CallStaticVoidMethod(g_bridgeClass, methodId, (jlong)instanceId, viewId, cornerRadius, tint, isDark);
    env->PopLocalFrame(nullptr);
    if (env->ExceptionCheck()) { nitro_report_jni_exception(env, env->ExceptionOccurred(), _nitro_err); }
}

void nitro_fold_duo_set_glass_capsule_menu(int64_t instanceId, int64_t viewId, int64_t buttonIndex, void* titles, void* symbols, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return; }
    jmethodID methodId = g_mid_setGlassCapsuleMenu_call;
    if (methodId == nullptr) { LOGE("Method not found: setGlassCapsuleMenu_call sig=(JJJ[B[B)V"); return; }

    nitro_fold_duo_clear_error();
    if (env->PushLocalFrame(16) != 0) { return; }
    int32_t titles_payload_len = *((const int32_t*)titles);
    int32_t titles_total = titles_payload_len + 4;
    jbyteArray j_titles = env->NewByteArray((jsize)titles_total);
    env->SetByteArrayRegion(j_titles, 0, (jsize)titles_total, (const jbyte*)titles);
    int32_t symbols_payload_len = *((const int32_t*)symbols);
    int32_t symbols_total = symbols_payload_len + 4;
    jbyteArray j_symbols = env->NewByteArray((jsize)symbols_total);
    env->SetByteArrayRegion(j_symbols, 0, (jsize)symbols_total, (const jbyte*)symbols);
    env->CallStaticVoidMethod(g_bridgeClass, methodId, (jlong)instanceId, viewId, buttonIndex, j_titles, j_symbols);
    env->PopLocalFrame(nullptr);
    if (env->ExceptionCheck()) { nitro_report_jni_exception(env, env->ExceptionOccurred(), _nitro_err); }
}

void nitro_fold_duo_register_state_changes_stream(int64_t instanceId, int64_t dart_port) {
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return; }
    jmethodID methodId = g_mid_nitro_fold_duo_register_state_changes_stream_call;
    if (methodId == nullptr) { LOGE("Method not found: nitro_fold_duo_register_state_changes_stream_call sig=(JJ)V"); return; }
    env->CallStaticVoidMethod(g_bridgeClass, methodId, (jlong)instanceId, dart_port);
}

void nitro_fold_duo_release_state_changes_stream(int64_t dart_port) {
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return; }
    jmethodID methodId = g_mid_nitro_fold_duo_release_state_changes_stream_call;
    if (methodId == nullptr) { LOGE("Method not found: nitro_fold_duo_release_state_changes_stream_call sig=(J)V"); return; }
    env->CallStaticVoidMethod(g_bridgeClass, methodId, dart_port);
}

JNIEXPORT jboolean JNICALL Java_nitro_nitro_1fold_1duo_1module_NitroFoldDuoJniBridge_emit_1stateChanges(JNIEnv* env, jobject thiz, jlong dartPort, jbyteArray item) {
    Dart_CObject obj;
    jsize len = env->GetArrayLength(item);
    uint8_t* buf = (uint8_t*)malloc((size_t)len);
    env->GetByteArrayRegion(item, 0, len, (jbyte*)buf);
    obj.type = Dart_CObject_kInt64;
    obj.value.as_int64 = (intptr_t)buf;
    if (!Dart_PostCObject_DL(dartPort, &obj)) {
        free(buf);
        return JNI_FALSE;
    }
    return JNI_TRUE;
}

void nitro_fold_duo_register_glass_capsule_presses_stream(int64_t instanceId, int64_t dart_port) {
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return; }
    jmethodID methodId = g_mid_nitro_fold_duo_register_glass_capsule_presses_stream_call;
    if (methodId == nullptr) { LOGE("Method not found: nitro_fold_duo_register_glass_capsule_presses_stream_call sig=(JJ)V"); return; }
    g_nitro_batch_nitro_fold_duo.coalesce(dart_port);
    env->CallStaticVoidMethod(g_bridgeClass, methodId, (jlong)instanceId, dart_port);
}

void nitro_fold_duo_release_glass_capsule_presses_stream(int64_t dart_port) {
    JNIEnv* env = GetEnv();
    if (env == nullptr) { return; }
    jmethodID methodId = g_mid_nitro_fold_duo_release_glass_capsule_presses_stream_call;
    if (methodId == nullptr) { LOGE("Method not found: nitro_fold_duo_release_glass_capsule_presses_stream_call sig=(J)V"); return; }
    env->CallStaticVoidMethod(g_bridgeClass, methodId, dart_port);
    g_nitro_batch_nitro_fold_duo.uncoalesce(dart_port);
}

JNIEXPORT jboolean JNICALL Java_nitro_nitro_1fold_1duo_1module_NitroFoldDuoJniBridge_emit_1glassCapsulePresses(JNIEnv* env, jobject thiz, jlong dartPort, jbyteArray item) {
    Dart_CObject obj;
    jsize len = env->GetArrayLength(item);
    uint8_t* buf = (uint8_t*)malloc((size_t)len);
    env->GetByteArrayRegion(item, 0, len, (jbyte*)buf);
    obj.type = Dart_CObject_kInt64;
    obj.value.as_int64 = (intptr_t)buf;
    if (!Dart_PostCObject_DL(dartPort, &obj)) {
        free(buf);
        return JNI_FALSE;
    }
    return JNI_TRUE;
}

JNIEXPORT void JNICALL Java_nitro_nitro_1fold_1duo_1module_NitroFoldDuoJniBridge_initialize(JNIEnv* env, jobject thiz, jclass localClass) {
    if (g_bridgeClass == nullptr) {
        g_bridgeClass = (jclass)env->NewGlobalRef(localClass);
        env->DeleteLocalRef(localClass);
    }
    // Re-cache method IDs every time (safe; idempotent; works even if JNI_OnLoad
    // could not find the app class. initialize() is called from Kotlin with the
    // correct class loader.)
    if (g_bridgeClass != nullptr) {
        // Cache bridge method IDs
        // Each GetStaticMethodID is followed by an ExceptionClear() guard:
        // if ANY lookup fails it throws NoSuchMethodError, and calling the
        // NEXT GetStaticMethodID with a pending exception aborts the JVM on
        // Android >= API 26 (strict JNI mode). Clearing after each failure
        // lets the remaining lookups proceed and logs the missing method.
        g_mid_create_instance_call = env->GetStaticMethodID(g_bridgeClass, "create_instance_call", "(Ljava/lang/String;)J");
        if (!g_mid_create_instance_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: create_instance_call sig=(Ljava/lang/String;)J"); }
        g_mid_destroy_instance_call = env->GetStaticMethodID(g_bridgeClass, "destroy_instance_call", "(J)V");
        if (!g_mid_destroy_instance_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: destroy_instance_call sig=(J)V"); }
        g_mid_currentState_call = env->GetStaticMethodID(g_bridgeClass, "currentState_call", "(J)[B");
        if (!g_mid_currentState_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: currentState_call sig=(J)[B"); }
        g_mid_updateGlassCapsule_call = env->GetStaticMethodID(g_bridgeClass, "updateGlassCapsule_call", "(JJ[B[BJJDZ)V");
        if (!g_mid_updateGlassCapsule_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: updateGlassCapsule_call sig=(JJ[B[BJJDZ)V"); }
        g_mid_updateGlassSurface_call = env->GetStaticMethodID(g_bridgeClass, "updateGlassSurface_call", "(JJDJZ)V");
        if (!g_mid_updateGlassSurface_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: updateGlassSurface_call sig=(JJDJZ)V"); }
        g_mid_setGlassCapsuleMenu_call = env->GetStaticMethodID(g_bridgeClass, "setGlassCapsuleMenu_call", "(JJJ[B[B)V");
        if (!g_mid_setGlassCapsuleMenu_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: setGlassCapsuleMenu_call sig=(JJJ[B[B)V"); }
        g_mid_nitro_fold_duo_register_state_changes_stream_call = env->GetStaticMethodID(g_bridgeClass, "nitro_fold_duo_register_state_changes_stream_call", "(JJ)V");
        if (!g_mid_nitro_fold_duo_register_state_changes_stream_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: nitro_fold_duo_register_state_changes_stream_call sig=(JJ)V"); }
        g_mid_nitro_fold_duo_release_state_changes_stream_call = env->GetStaticMethodID(g_bridgeClass, "nitro_fold_duo_release_state_changes_stream_call", "(J)V");
        if (!g_mid_nitro_fold_duo_release_state_changes_stream_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: nitro_fold_duo_release_state_changes_stream_call sig=(J)V"); }
        g_mid_nitro_fold_duo_register_glass_capsule_presses_stream_call = env->GetStaticMethodID(g_bridgeClass, "nitro_fold_duo_register_glass_capsule_presses_stream_call", "(JJ)V");
        if (!g_mid_nitro_fold_duo_register_glass_capsule_presses_stream_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: nitro_fold_duo_register_glass_capsule_presses_stream_call sig=(JJ)V"); }
        g_mid_nitro_fold_duo_release_glass_capsule_presses_stream_call = env->GetStaticMethodID(g_bridgeClass, "nitro_fold_duo_release_glass_capsule_presses_stream_call", "(J)V");
        if (!g_mid_nitro_fold_duo_release_glass_capsule_presses_stream_call && env->ExceptionCheck()) { env->ExceptionClear(); LOGE("Method not found: nitro_fold_duo_release_glass_capsule_presses_stream_call sig=(J)V"); }
    }

    // Cache DuoState class + encode() for stream serialisation
    {
        jclass local_cls_DuoState = env->FindClass("nitro/nitro_fold_duo_module/DuoState");
        if (local_cls_DuoState != nullptr) {
            g_cls_DuoState = (jclass)env->NewGlobalRef(local_cls_DuoState);
            env->DeleteLocalRef(local_cls_DuoState);
            g_mid_DuoState_encode = env->GetMethodID(g_cls_DuoState, "encode", "()[B");
        } else {
            LOGE("Failed to find class nitro/nitro_fold_duo_module/DuoState");
        }
    }
    // Cache DuoBarPress class + encode() for stream serialisation
    {
        jclass local_cls_DuoBarPress = env->FindClass("nitro/nitro_fold_duo_module/DuoBarPress");
        if (local_cls_DuoBarPress != nullptr) {
            g_cls_DuoBarPress = (jclass)env->NewGlobalRef(local_cls_DuoBarPress);
            env->DeleteLocalRef(local_cls_DuoBarPress);
            g_mid_DuoBarPress_encode = env->GetMethodID(g_cls_DuoBarPress, "encode", "()[B");
        } else {
            LOGE("Failed to find class nitro/nitro_fold_duo_module/DuoBarPress");
        }
    }
}

} // extern "C"
#elif __APPLE__
extern "C" {
extern void* _nitro_fold_duo_call_currentState(void);
void* nitro_fold_duo_current_state(int64_t instanceId, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
#ifdef __OBJC__
    @try {
        return _nitro_fold_duo_call_currentState();
    } @catch (NSException* e) {
        if (_nitro_err) {
            // sync: write exception to out-param error slot.
            _nitro_err->hasError = 1;
            _nitro_err->name    = strdup([e.name UTF8String]);
            _nitro_err->message = strdup([e.reason UTF8String]);
            _nitro_err->code = nullptr;
            _nitro_err->stackTrace = nullptr;
        } else {
            // async: _nitro_err is null — route exception to TLS slot.
            nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);
        }
        return nullptr;
    }
#else
    return _nitro_fold_duo_call_currentState();
#endif
}

extern void _nitro_fold_duo_call_updateGlassCapsule(int64_t viewId, void* symbols, void* titles, int64_t selectedIndex, int64_t tint, double symbolPointSize, int8_t isDark);
void nitro_fold_duo_update_glass_capsule(int64_t instanceId, int64_t viewId, void* symbols, void* titles, int64_t selectedIndex, int64_t tint, double symbolPointSize, int8_t isDark, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
#ifdef __OBJC__
    @try {
        _nitro_fold_duo_call_updateGlassCapsule(viewId, symbols, titles, selectedIndex, tint, symbolPointSize, isDark);
    } @catch (NSException* e) {
        if (_nitro_err) {
            // sync: write exception to out-param error slot.
            _nitro_err->hasError = 1;
            _nitro_err->name    = strdup([e.name UTF8String]);
            _nitro_err->message = strdup([e.reason UTF8String]);
            _nitro_err->code = nullptr;
            _nitro_err->stackTrace = nullptr;
        } else {
            // async: _nitro_err is null — route exception to TLS slot.
            nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);
        }
    }
#else
    _nitro_fold_duo_call_updateGlassCapsule(viewId, symbols, titles, selectedIndex, tint, symbolPointSize, isDark);
#endif
}

extern void _nitro_fold_duo_call_updateGlassSurface(int64_t viewId, double cornerRadius, int64_t tint, int8_t isDark);
void nitro_fold_duo_update_glass_surface(int64_t instanceId, int64_t viewId, double cornerRadius, int64_t tint, int8_t isDark, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
#ifdef __OBJC__
    @try {
        _nitro_fold_duo_call_updateGlassSurface(viewId, cornerRadius, tint, isDark);
    } @catch (NSException* e) {
        if (_nitro_err) {
            // sync: write exception to out-param error slot.
            _nitro_err->hasError = 1;
            _nitro_err->name    = strdup([e.name UTF8String]);
            _nitro_err->message = strdup([e.reason UTF8String]);
            _nitro_err->code = nullptr;
            _nitro_err->stackTrace = nullptr;
        } else {
            // async: _nitro_err is null — route exception to TLS slot.
            nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);
        }
    }
#else
    _nitro_fold_duo_call_updateGlassSurface(viewId, cornerRadius, tint, isDark);
#endif
}

extern void _nitro_fold_duo_call_setGlassCapsuleMenu(int64_t viewId, int64_t buttonIndex, void* titles, void* symbols);
void nitro_fold_duo_set_glass_capsule_menu(int64_t instanceId, int64_t viewId, int64_t buttonIndex, void* titles, void* symbols, NitroError* _nitro_err) {
    if (_nitro_err) { _nitro_err->hasError = 0; }
#ifdef __OBJC__
    @try {
        _nitro_fold_duo_call_setGlassCapsuleMenu(viewId, buttonIndex, titles, symbols);
    } @catch (NSException* e) {
        if (_nitro_err) {
            // sync: write exception to out-param error slot.
            _nitro_err->hasError = 1;
            _nitro_err->name    = strdup([e.name UTF8String]);
            _nitro_err->message = strdup([e.reason UTF8String]);
            _nitro_err->code = nullptr;
            _nitro_err->stackTrace = nullptr;
        } else {
            // async: _nitro_err is null — route exception to TLS slot.
            nitro_report_error([e.name UTF8String], [e.reason UTF8String], nullptr, nullptr);
        }
    }
#else
    _nitro_fold_duo_call_setGlassCapsuleMenu(viewId, buttonIndex, titles, symbols);
#endif
}

bool _emit_stateChanges_to_dart(int64_t dartPort, void* item) {
    Dart_CObject obj;
    obj.type = Dart_CObject_kInt64;
    obj.value.as_int64 = (intptr_t)item;
    return Dart_PostCObject_DL(dartPort, &obj);
}

extern void _nitro_fold_duo_register_stateChanges_stream(int64_t dartPort, bool (*emitCb)(int64_t, void*));
void nitro_fold_duo_register_state_changes_stream(int64_t instanceId, int64_t dart_port) {
    _nitro_fold_duo_register_stateChanges_stream(dart_port, _emit_stateChanges_to_dart);
}
extern void _nitro_fold_duo_release_stateChanges_stream(int64_t dart_port);
void nitro_fold_duo_release_state_changes_stream(int64_t dart_port) {
    _nitro_fold_duo_release_stateChanges_stream(dart_port);
}

bool _emit_glassCapsulePresses_to_dart(int64_t dartPort, void* item) {
    Dart_CObject obj;
    obj.type = Dart_CObject_kInt64;
    obj.value.as_int64 = (intptr_t)item;
    return Dart_PostCObject_DL(dartPort, &obj);
}

extern void _nitro_fold_duo_register_glassCapsulePresses_stream(int64_t dartPort, bool (*emitCb)(int64_t, void*));
void nitro_fold_duo_register_glass_capsule_presses_stream(int64_t instanceId, int64_t dart_port) {
    g_nitro_batch_nitro_fold_duo.coalesce(dart_port);
    _nitro_fold_duo_register_glassCapsulePresses_stream(dart_port, _emit_glassCapsulePresses_to_dart);
}
extern void _nitro_fold_duo_release_glassCapsulePresses_stream(int64_t dart_port);
void nitro_fold_duo_release_glass_capsule_presses_stream(int64_t dart_port) {
    _nitro_fold_duo_release_glassCapsulePresses_stream(dart_port);
    g_nitro_batch_nitro_fold_duo.uncoalesce(dart_port);
}

static int64_t nitro_fold_duo_g_next_instance_id = 0;
NITRO_EXPORT int64_t nitro_fold_duo_create_instance(const char* key) { (void)key; return nitro_fold_duo_g_next_instance_id++; }
NITRO_EXPORT void nitro_fold_duo_destroy_instance(int64_t instanceId) { (void)instanceId; }
NITRO_EXPORT void nitro_fold_duo_nitro_free(void* ptr) { if (ptr) { free(ptr); } }
NITRO_EXPORT void* nitro_fold_duo_nitro_alloc(size_t size) { return malloc(size); }

} // extern "C"
#elif defined(_WIN32) || defined(__linux__)  // Windows/Linux: NativeImpl.cpp — direct C++ dispatch
#include "nitro_fold_duo.native.g.h"

#include <algorithm>
#include <mutex>
#include <unordered_map>
#include <vector>

// One registry per stream, PARTITIONED BY INSTANCE: a stream belongs to
// the Hybrid<Class> that emits it, so a subscriber on one instance never
// receives another instance's events (the ports used to be global, so
// every subscriber saw every instance). Every concurrent Dart subscriber
// registers its own ReceivePort. Guarded by a mutex — register/release
// run on the Dart isolate thread while emits may come from any thread.
struct _NitroStreamPorts {
    std::mutex mtx;
    std::unordered_map<const void*, std::vector<int64_t>> byInstance;
    void add(const void* inst, int64_t p) {
        std::lock_guard<std::mutex> l(mtx); byInstance[inst].push_back(p);
    }
    // Release carries only the port: Dart cancels a subscription without
    // naming the instance, so drop it wherever it is registered.
    void remove(int64_t p) {
        std::lock_guard<std::mutex> l(mtx);
        for (auto& kv : byInstance) {
            auto& v = kv.second;
            v.erase(std::remove(v.begin(), v.end(), p), v.end());
        }
    }
    void dropInstance(const void* inst) {
        std::lock_guard<std::mutex> l(mtx); byInstance.erase(inst);
    }
    std::vector<int64_t> snapshot(const void* inst) {
        std::lock_guard<std::mutex> l(mtx);
        auto it = byInstance.find(inst);
        return it == byInstance.end() ? std::vector<int64_t>() : it->second;
    }
};
static _NitroStreamPorts g_ports_stateChanges;
static _NitroStreamPorts g_ports_glassCapsulePresses;

// Called by destroy_instance so a disposed instance leaves no subscribers.
void _nitro_release_instance_streams(const void* impl) {
    g_ports_stateChanges.dropInstance(impl);
    g_ports_glassCapsulePresses.dropInstance(impl);
}

void HybridNitroFoldDuo::emit_stateChanges(NitroCppBuffer item) {
    auto _ports = g_ports_stateChanges.snapshot(this);
    if (_ports.empty()) { if (item.data) { free((void*)item.data); } return; }
    Dart_CObject obj;
    if (item.data == nullptr) {
        obj.type = Dart_CObject_kNull;
        for (int64_t _port : _ports) {
            if (!Dart_PostCObject_DL(_port, &obj)) { g_ports_stateChanges.remove(_port); }
        }
        return;
    }
    for (int64_t _port : _ports) {
        uint8_t* _copy = (uint8_t*)malloc(item.size);
        if (!_copy) { break; }
        memcpy(_copy, item.data, item.size);
        obj.type = Dart_CObject_kInt64;
        obj.value.as_int64 = (intptr_t)_copy;
        if (!Dart_PostCObject_DL(_port, &obj)) {
            free(_copy);
            g_ports_stateChanges.remove(_port);
        }
    }
    free((void*)item.data);
}

void HybridNitroFoldDuo::emit_glassCapsulePresses(NitroCppBuffer item) {
    auto _ports = g_ports_glassCapsulePresses.snapshot(this);
    if (_ports.empty()) { if (item.data) { free((void*)item.data); } return; }
    Dart_CObject obj;
    if (item.data == nullptr) {
        obj.type = Dart_CObject_kNull;
        for (int64_t _port : _ports) {
            if (!Dart_PostCObject_DL(_port, &obj)) { g_ports_glassCapsulePresses.remove(_port); }
        }
        return;
    }
    for (int64_t _port : _ports) {
        uint8_t* _copy = (uint8_t*)malloc(item.size);
        if (!_copy) { break; }
        memcpy(_copy, item.data, item.size);
        obj.type = Dart_CObject_kInt64;
        obj.value.as_int64 = (intptr_t)_copy;
        if (!Dart_PostCObject_DL(_port, &obj)) {
            free(_copy);
            g_ports_glassCapsulePresses.remove(_port);
        }
    }
    free((void*)item.data);
}

static void _nitro_desktop_err(NitroError* _out, const char* _name, const char* _message) {
    nitro_report_error(_name, _message, nullptr, nullptr);
    if (_out) {
        _out->hasError = 1;
        _out->name = _name ? strdup(_name) : nullptr;
        _out->message = _message ? strdup(_message) : nullptr;
        _out->code = nullptr;
        _out->stackTrace = nullptr;
    }
}

#include <atomic>
#include <memory>
#include <mutex>
#include <unordered_map>

using HybridNitroFoldDuoFactory = std::function<std::shared_ptr<HybridNitroFoldDuo>(const std::string&)>;
static std::unordered_map<int64_t, std::shared_ptr<HybridNitroFoldDuo>>& _g_instances() {
    static std::unordered_map<int64_t, std::shared_ptr<HybridNitroFoldDuo>> m;
    return m;
}
static std::mutex& _g_instances_mtx() {
    static std::mutex m;
    return m;
}
static std::atomic<int64_t>& _g_next_instance_id() {
    static std::atomic<int64_t> id{1};
    return id;
}
static HybridNitroFoldDuoFactory& _g_factory() {
    static HybridNitroFoldDuoFactory f;
    return f;
}

static constexpr int _kNitroCacheWays = 8;
struct alignas(64) _NitroInstSlot {
    std::atomic<int64_t> id{-1};
    std::atomic<HybridNitroFoldDuo*> ptr{nullptr};
};
static _NitroInstSlot _g_inst_cache[_kNitroCacheWays];
static HybridNitroFoldDuo* _nitro_get_instance(int64_t id) {
    _NitroInstSlot& _slot = _g_inst_cache[(uint64_t)id & (_kNitroCacheWays - 1)];
    if (_slot.id.load(std::memory_order_acquire) == id) {
        return _slot.ptr.load(std::memory_order_relaxed);
    }
    std::lock_guard<std::mutex> _lk(_g_instances_mtx());
    auto it = _g_instances().find(id);
    HybridNitroFoldDuo* p = (it != _g_instances().end()) ? it->second.get() : nullptr;
    if (p) {
        _slot.ptr.store(p, std::memory_order_relaxed);
        _slot.id.store(id, std::memory_order_release);
    }
    return p;
}
static void _nitro_invalidate_cache() {
    for (int _i = 0; _i < _kNitroCacheWays; ++_i) {
        _g_inst_cache[_i].id.store(-1, std::memory_order_release);
        _g_inst_cache[_i].ptr.store(nullptr, std::memory_order_relaxed);
    }
}

// Defined with the stream registries below (which may be emitted after
// this block): drops every subscriber belonging to one instance.
void _nitro_release_instance_streams(const void* impl);

extern "C" {
void nitro_fold_duo_register_factory(void* fn) {
    _g_factory() = *static_cast<HybridNitroFoldDuoFactory*>(fn);
}
void nitro_fold_duo_register_impl(HybridNitroFoldDuo* impl) {
    std::lock_guard<std::mutex> _lk(_g_instances_mtx());
    if (impl) _g_instances()[0] = std::shared_ptr<HybridNitroFoldDuo>(impl, [](HybridNitroFoldDuo*){});
    else _g_instances().erase(0);
    _nitro_invalidate_cache();
}
HybridNitroFoldDuo* nitro_fold_duo_get_impl() {
    return _nitro_get_instance(0);
}
NITRO_EXPORT int64_t nitro_fold_duo_create_instance(const char* key) {
    if (_g_factory()) {
        auto inst = _g_factory()(key ? key : "");
        if (!inst) return -1;
        std::lock_guard<std::mutex> _lk(_g_instances_mtx());
        int64_t id = ++_g_next_instance_id();
        _g_instances()[id] = std::move(inst);
        return id;
    }
      // Legacy: no factory registered — return 0 (single global impl slot)
    return 0;
}
NITRO_EXPORT void nitro_fold_duo_destroy_instance(int64_t instanceId) {
    // Slot 0 belongs to register_impl (the legacy single impl and the
    // stream-emitter target), never to a Dart instance. Without this a
    // plugin that registers no factory hands every instance id 0, and the
    // first dispose() erases the slot for all of them.
    if (instanceId == 0) { return; }
    std::lock_guard<std::mutex> _lk(_g_instances_mtx());
    auto _it = _g_instances().find(instanceId);
    if (_it != _g_instances().end()) {
        _nitro_release_instance_streams(_it->second.get());
    }
    _g_instances().erase(instanceId);
    _nitro_invalidate_cache();
}
NITRO_EXPORT void nitro_fold_duo_nitro_free(void* ptr) { if (ptr) { free(ptr); } }
NITRO_EXPORT void* nitro_fold_duo_nitro_alloc(size_t size) { return malloc(size); }

void* nitro_fold_duo_current_state(int64_t instanceId, NitroError* _nitro_err) {
    nitro_fold_duo_clear_error();
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_fold_duo_register_impl() first."); return nullptr; }
    try {
        NitroCppBuffer _res = _impl->currentState();
        return (void*)_res.data;
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
        return nullptr;
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
        return nullptr;
    }
}

void nitro_fold_duo_update_glass_capsule(int64_t instanceId, int64_t viewId, void* symbols, void* titles, int64_t selectedIndex, int64_t tint, double symbolPointSize, int8_t isDark, NitroError* _nitro_err) {
    nitro_fold_duo_clear_error();
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_fold_duo_register_impl() first."); return; }
    try {
        NitroCppBuffer _buf_symbols = { (const uint8_t*)symbols + 4, (size_t)*(int32_t*)symbols };
        NitroCppBuffer _buf_titles = { (const uint8_t*)titles + 4, (size_t)*(int32_t*)titles };
        _impl->updateGlassCapsule(viewId, _buf_symbols, _buf_titles, selectedIndex, tint, symbolPointSize, isDark);
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_fold_duo_update_glass_surface(int64_t instanceId, int64_t viewId, double cornerRadius, int64_t tint, int8_t isDark, NitroError* _nitro_err) {
    nitro_fold_duo_clear_error();
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_fold_duo_register_impl() first."); return; }
    try {
        _impl->updateGlassSurface(viewId, cornerRadius, tint, isDark);
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_fold_duo_set_glass_capsule_menu(int64_t instanceId, int64_t viewId, int64_t buttonIndex, void* titles, void* symbols, NitroError* _nitro_err) {
    nitro_fold_duo_clear_error();
    if (_nitro_err) { _nitro_err->hasError = 0; }  // S8: clear slot
    auto _impl = _nitro_get_instance(instanceId);
    if (!_impl) { _nitro_desktop_err(_nitro_err, "NotInitialized", "No C++ implementation registered. Call nitro_fold_duo_register_impl() first."); return; }
    try {
        NitroCppBuffer _buf_titles = { (const uint8_t*)titles + 4, (size_t)*(int32_t*)titles };
        NitroCppBuffer _buf_symbols = { (const uint8_t*)symbols + 4, (size_t)*(int32_t*)symbols };
        _impl->setGlassCapsuleMenu(viewId, buttonIndex, _buf_titles, _buf_symbols);
    } catch (const std::exception& e) {
        _nitro_desktop_err(_nitro_err, "CppException", e.what());
    } catch (...) {
        _nitro_desktop_err(_nitro_err, "CppException", "Unknown C++ exception");
    }
}

void nitro_fold_duo_register_state_changes_stream(int64_t instanceId, int64_t dart_port) {
    g_ports_stateChanges.add(_nitro_get_instance(instanceId), dart_port);
}
void nitro_fold_duo_release_state_changes_stream(int64_t dart_port) {
    g_ports_stateChanges.remove(dart_port);
}

void nitro_fold_duo_register_glass_capsule_presses_stream(int64_t instanceId, int64_t dart_port) {
    g_nitro_batch_nitro_fold_duo.coalesce(dart_port);
    g_ports_glassCapsulePresses.add(_nitro_get_instance(instanceId), dart_port);
}
void nitro_fold_duo_release_glass_capsule_presses_stream(int64_t dart_port) {
    g_ports_glassCapsulePresses.remove(dart_port);
    g_nitro_batch_nitro_fold_duo.uncoalesce(dart_port);
}

} // extern "C"
#endif
