// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.7.6
// Generated from: nitro_fold_duo.native.dart
// spec-sha256: eabc08029258b07aaf4fdd1036323c0cbf6ace70dc03abef9ba237c54b478462
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

#ifndef NITRO_EXPORT
#  if defined(_WIN32)
#    define NITRO_EXPORT __declspec(dllexport)
#  else
#    define NITRO_EXPORT __attribute__((visibility("default"))) __attribute__((used))
#  endif
#endif

#ifndef NITRO_ERROR_DEFINED
#define NITRO_ERROR_DEFINED
typedef struct {
  int8_t hasError;
  const char* name;
  const char* message;
  const char* code;
  const char* stackTrace;
} NitroError;
#endif

#ifndef NITRO_OPT_DEFINED
#define NITRO_OPT_DEFINED
#pragma pack(push, 1)
typedef struct { uint8_t hasValue; int64_t  value; } NitroOptInt64;
typedef struct { uint8_t hasValue; double   value; } NitroOptFloat64;
typedef struct { uint8_t hasValue; uint8_t  value; } NitroOptBool;
#pragma pack(pop)
#endif

#ifdef __cplusplus
extern "C" {
#endif

NITRO_EXPORT uint32_t nitro_fold_duo_nitro_abi_version(void);
NITRO_EXPORT const char* nitro_fold_duo_nitro_bridge_checksum(void);
NITRO_EXPORT intptr_t nitro_fold_duo_init_dart_api_dl(void* data);
NITRO_EXPORT NitroError* nitro_fold_duo_get_error(void);
NITRO_EXPORT void nitro_fold_duo_clear_error(void);
NITRO_EXPORT int64_t nitro_fold_duo_create_instance(const char* key);
NITRO_EXPORT void nitro_fold_duo_destroy_instance(int64_t instanceId);
NITRO_EXPORT void nitro_fold_duo_nitro_free(void* ptr);
NITRO_EXPORT void* nitro_fold_duo_nitro_alloc(size_t size);
struct _Dart_CObject;
NITRO_EXPORT bool nitro_fold_duo_nitro_post(int64_t port, struct _Dart_CObject* obj);
NITRO_EXPORT int64_t nitro_fold_duo_nitro_bind(int64_t batchPort);
NITRO_EXPORT void nitro_fold_duo_nitro_ack(int64_t batchPort);
#define Dart_PostCObject_DL(port, obj) nitro_fold_duo_nitro_post((port), (obj))



// Methods
NITRO_EXPORT double nitro_fold_duo_add(int64_t instanceId, double a, double b, NitroError* _nitro_err);
NITRO_EXPORT const char* nitro_fold_duo_get_greeting(int64_t instanceId, const char* name);
NITRO_EXPORT void nitro_fold_duo_get_greeting_dispatch(int64_t instanceId, const char* name, NitroError* _nitro_err, int64_t dart_port);

#ifdef __cplusplus
}
#endif
